import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";

import {
  getAllPosts,
  getPostsByPage,
  getPostsForTopPage,
} from "../../../lib/notionAPI";
import SinglePost from "@/components/post/SinglePost";

export const getStaticPaths: GetStaticPaths = async () => {

  return {
    paths: [{params: {page: "1"}}, {params: {page: "2"}}],
    fallback: "blocking",
  };
};

export const getStaticProps: GetStaticProps = async (context) => {
  const currentPage = context.params?.page;
  const postsByPage = await getPostsByPage(
    parseInt(currentPage.toString(), 10)
  );

  return {
    props: {
      postsByPage,
    },
    revalidate: 10,
  };
};

const BlogPageList = ({ postsByPage }) => {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">
          Notion Blog🚀
        </h1>
        <section className="sm:grid grid-cols-2 w-5/6 gap-3 mx-auto">
          {postsByPage.map((post) => (
            <div key={post.id}>
              <SinglePost
                title={post.title}
                description={post.description}
                tags={post.tags}
                slug={post.slug}
                isPaginationPage={true}
              />
            </div>
          ))}
        </section>
      </main>
    </div>
  );
};

export default BlogPageList;
