import { GetServerSideProps } from "next";
import Head from "next/head";
import Link from "next/link";

import {
  getAllTags,
  getNumberOfPages,
  getPostsByPage,
} from "../../../lib/notionAPI";

import { BlogPageListProps } from "@/types/Type";

import SinglePost from "@/components/post/SinglePost";
import Pagination from "@/components/Pagination/pagination";
import Tag from "@/components/Tag/Tag";


export const getServerSideProps: GetServerSideProps = async (context) => {
  const currentPage = context.params?.page ?? "1";


  const postsByPage = await getPostsByPage(
    parseInt(currentPage.toString(), 10)
  );

  const numberOfPage = await getNumberOfPages();

  const allTags = await getAllTags();

  return {
    props: {
      postsByPage,
      numberOfPage,
      allTags,
    },
  };
};

const BlogPageList = ({ postsByPage, numberOfPage, allTags }: BlogPageListProps) => {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>gachadex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <Link href={`/`}>
          <h1 className="text-5xl font-medium text-center mb-16">
            gachadex😄
          </h1>
        </Link>
        <Tag tags={allTags} />
        <section className="sm:grid grid-cols-2 w-5/6 gap-3 mx-auto">
          {postsByPage.map((post) => (
            <div key={post.id}>
              <SinglePost
                title={post.title}
                description={post.description}
                tags={post.tags}
                slug={post.slug}
                cover={post.cover}
              />
            </div>
          ))}
        </section>
        <Pagination numberOfPage={numberOfPage} tag={""} />
      </main>
    </div>
  );
};

export default BlogPageList;
