import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";

import {
  getNumberOfPages,
  getPostsByPage,
} from "../../../lib/notionAPI";

import SinglePost from "@/components/post/SinglePost";
import Pagination from "@/components/Pagination/pagination";


export const getStaticPaths: GetStaticPaths = async () => {
  //ページネーションの中にある現在のページを返す
  const numberOfPage = await getNumberOfPages();

  //該当箇所を返す
  let params = [];
  for (let i = 1; i <= numberOfPage; i++) {
    params.push({ params: { page: i.toString() } });
  }

  return {
    paths: params,
    fallback: "blocking",
  };
};

export const getStaticProps: GetStaticProps = async (context) => {
  //現在のページ
  const currentPage = context.params?.page;

  //そのページの個数を数値で取得
  const postsByPage = await getPostsByPage(
    parseInt(currentPage.toString(), 10)
  );

  //ページネーション設定
  const numberOfPage = await getNumberOfPages();

  return {
    props: {
      postsByPage,
      numberOfPage,
    },
    revalidate: 10,
  };
};

const BlogPageList = ({ postsByPage, numberOfPage  }) => {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">
          Notion Blog🚀
        </h1>
        <section className="sm:grid grid-cols-2 w-5/6 gap-3 mx-auto">
          {postsByPage.map((post) => (
            <div key={post.id}>
              <SinglePost
                title={post.title}
                description={post.description}
                tags={post.tags}
                slug={post.slug}
                isPaginationPage={true}
              />
            </div>
          ))}
        </section>
        <Pagination numberOfPage={numberOfPage} tag={""} />
      </main>
    </div>
  );
};

export default BlogPageList;
